- name: Ensure Local Directories Exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'
  loop:
    - "{{ seafile_root }}"
    - "{{ seafile_root }}/seafile-data"
    - "{{ seafile_root }}/mariadb"

- name: Render Docker Compose
  ansible.builtin.template:
    src: templates/seafile_compose.yaml.j2
    dest: "{{ seafile_root }}/docker-compose.yml"
    mode: "0644"

- name: Spin up Seafile Stack
  community.docker.docker_compose_v2:
    project_src: "{{ seafile_root }}"
    state: present
    pull: always
    wait: true

- name: Find the seahub config directory natively
  ansible.builtin.find:
    paths: "{{ seafile_root }}/seafile-data"
    file_type: directory
    patterns: "conf"
    recurse: true
  register: seafile_found_dirs
  until: seafile_found_dirs.matched > 0
  retries: 20
  delay: 5
  changed_when: false

- name: Set seahub configuration path
  ansible.builtin.set_fact:
    seafile_seahub_conf_dir: "{{ item.path }}"
  loop: "{{ seafile_found_dirs.files }}"
  # Targets the specific config folder inside the shared volume
  when: "'seafile/conf' in item.path"
  changed_when: false

- name: Wait for seahub_settings.py to be generated
  ansible.builtin.wait_for:
    path: "{{ seafile_seahub_conf_dir }}/seahub_settings.py"
    state: present
    timeout: 120

- name: Inject SSO Configuration into Seahub Settings
  ansible.builtin.blockinfile:
    path: "{{ seafile_seahub_conf_dir }}/seahub_settings.py"
    block: |
      ENABLE_OAUTH = True
      OAUTH_ENABLE_INSECURE_TRANSPORT = True
      OAUTH_VERIFY_EMAIL = False
      OAUTH_CLIENT_ID = '{{ vault_seafile_client_id }}'
      OAUTH_CLIENT_SECRET = '{{ vault_seafile_client_secret }}'
      OAUTH_REDIRECT_URL = 'https://seafile.potterman.party/oauth/callback/'
      OAUTH_PROVIDER = 'authentik'
      OAUTH_PROVIDER_DOMAIN = 'auth.potterman.party'
      OAUTH_AUTHORIZATION_URL = 'https://auth.potterman.party/application/o/authorize/'
      OAUTH_TOKEN_URL = 'https://auth.potterman.party/application/o/token/'
      OAUTH_USER_INFO_URL = 'https://auth.potterman.party/application/o/userinfo/'
      OAUTH_SCOPE = ['openid', 'profile', 'email']

      OAUTH_ATTRIBUTE_MAP = {
          "email": (True, "contact_email"),
          "name": (False, "name"),
          "sub": (False, "uid"),
      }
      LOGIN_URL = 'https://seafile.potterman.party/oauth/login/'

      OAUTH_CREATE_UNKNOWN_USER = True
      OAUTH_ACTIVATE_USER_AFTER_CREATION = True
      CSRF_TRUSTED_ORIGINS = ['https://seafile.potterman.party']
      CLIENT_SSO_VIA_LOCAL_BROWSER = True
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SSO CONFIG"
  notify: Restart Seafile
