- name: Create Authentik Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1000"   # The UID Authentik expects
    group: "1000"   # The GID Authentik expects
    mode: '0755'
  loop:
    - "{{ app_services.authentik.root_path }}"
    - "{{ app_services.authentik.root_path }}/media"
    - "{{ app_services.authentik.root_path }}/certs"
    - "{{ app_services.authentik.root_path }}/custom-templates"

- name: Render .env File
  ansible.builtin.template:
    src: templates/authentik_env.j2
    dest: "{{ app_services.authentik.root_path }}/.env"
    mode: '0600'

- name: Render Docker Compose
  ansible.builtin.template:
    src: templates/authentik_compose.yaml.j2
    dest: "{{ app_services.authentik.root_path }}/docker-compose.yml"
    mode: '0600'

- name: Start Authentik Stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_services.authentik.root_path }}"
    state: present
    pull: always

- name: Wait for Authentik Server (Port 9000)
  ansible.builtin.wait_for:
    port: 9000
    delay: 15
    timeout: 120
