name: Mirror to GitHub
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub
        run: |
          git remote add github https://${{ secrets.GH_TOKEN }}@github.com/potterman/homelab.git
          git push github main --force
