- name: Ensure Hoodik directory exists
  ansible.builtin.file:
    path: "{{ app_services.hoodik.root_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: hoodik

- name: Render Docker Compose
  ansible.builtin.template:
    src: templates/hoodik_compose.yaml.j2
    dest: "{{ app_services.hoodik.root_path }}/docker-compose.yml"
    mode: "0644"
  notify: Recreate Hoodik Stack
  tags: hoodik

- name: Start Hoodik Stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_services.hoodik.root_path }}"
    state: present
    pull: always
    wait: true
  tags: hoodik
