- name: Deploy Homepage Dashboard
  hosts: debian-docker
  become: true
  tasks:

    - name: Ensure Homepage config directory exists with correct permissions
      ansible.builtin.file:
        path: /opt/homepage/config
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'
        recurse: true

    - name: Deploy Homepage Container
      community.docker.docker_container:
        name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3005:3000"
        volumes:
          - /opt/homepage/config:/app/config
          - /var/run/docker.sock:/var/run/docker.sock:ro


- name: Deploy Caddy | Playbook Handoff
  ansible.builtin.import_playbook: deploy_caddy.yml

