---
- name: Deploy Homepage Dashboard Container
  hosts: debian-docker
  become: true
  tasks:
    - name: Ensure Docker Environment is there
      ansible.builtin.include_tasks: tasks/install_docker.yml

    - name: Start Homepage Container
      community.docker.docker_container:
        name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3005:3000"
        volumes:
          - "{{ homepage_root }}/config:/app/config"
          - /var/run/docker.sock:/var/run/docker.sock:ro
        # Optional: Add env vars if needed
        env:
          PUID: "1000"
          PGID: "1000"
          HOMEPAGE_ALLOWED_HOSTS: "home.potterman.party,localhost,127.0.0.1"
