docker_base_path: /opt
authentik_root: "{{ docker_base_path }}/authentik"
homepage_root: "{{ docker_base_path }}/homepage"
seafile_root: "{{ docker_base_path }}/seafile"
teamspeak_root: "{{ docker_base_path}}/teamspeak"
seafile_nas_mount: "/mnt/NAS_ZFS/seafile-data"
