# This is the file that stores data of the services
# Domain names, subdomains, ports etc. for Caddy automation

global_docker_base_path: "/opt"
global_nas_mount_path: "/mnt/NAS_ZFS"
global_timezone: "Europe/Warsaw"

app_services:
  pihole:
    version: "2025.11.1"
    subdomain: "pihole"
    domain: "potterman.party"
    internal_port: 800
    root_path: "{{ global_docker_base_path }}/pihole"

  paperless:
    subdomain: "paperless"
    domain: "potterman.party"
    image: "ghcr.io/paperless-ngx/paperless-ngx"
    version: "2.16.3"
    internal_port: 8000
    root_path: "{{ global_docker_base_path }}/paperless"
    consume_path: "{{ global_nas_mount_path }}/paperless/consume"
    backup_path: "{{ global_nas_mount_path }}/paperless/backup"
    redis_image: "redis"
    redis_version: "7-alpine"
    postgres_image: "postgres"
    postgres_version: "16-alpine"
    gotenberg_image: "gotenberg/gotenberg"
    gotenberg_version: "8"
    tika_image: "apache/tika"
    tika_version: "3.2.0.0"

  firefly:
    subdomain: "firefly"
    domain: "potterman.party"
    internal_port: 8090
    root_path: "{{ global_docker_base_path }}/firefly"

  foundryvtt:
    foundry_version: "13.351"
    subdomain: "foundry"
    domain: "potterman.party"
    internal_port: 30000
    root_path: "{{ global_docker_base_path }}/foundryvtt"
    foundry_user_data_path: "{{ global_nas_mount_path }}/foundryvtt/foundry_user_data"

  authentik:
    subdmain: "auth"
    domain: "potterman.party"
    internal_port: 9000
    root_path: "{{ global_docker_base_path }}/authentik"

  seafile:
    subdomain: "seafile"
    domain: "potterman.party"
    internal_port: 8060
    protocols: "h1 h2"
    root_path: "{{ global_docker_base_path }}/seafile"

  homepage:
    subdmain: "homepage"
    domain: "potterman.party"
    internal_port: 3005
    root_path: "{{ global_docker_base_path }}/homepage"

  garage:
    type: "k3"
    subdomain: "s3"
    domain: "potterman.party"
    internal_port: 7777
