cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
zerotier_network_id: "{{ vault_zerotier_network_id }}"
seafile_db_password: "{{ vault_seafile_db_password }}"
seafile_client_id: "{{ vault_seafile_client_id }}"
seafile_client_secret: "{{ vault_seafile_client_secret }}"
authentik_pg_password: "{{ vault_authentik_pg_password }}"
authentik_secret_key: "{{ vault_authentik_secret_key }}"
seafile_secret_key: "{{ vault_seafile_secret_key }}"
firefly_static_cron_token: "{{ vault_firefly_static_cron_token }}"
firefly_db_password: "{{ vault_firefly_db_password }}"
firefly_app_key: "{{ vault_firefly_app_key }}"
